server:
  port: 8090
  servlet:
    context-path: /young-artist-app

spring:
  application:
    name: YoungArtist
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: UDHdQtwHrWlRVJfMJXxAjSFfIcTnlmwA
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    org.springframework.security: trace